image: azul/zulu-openjdk:21

variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=/cache/maven.repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "-C --batch-mode --errors --fail-at-end --show-version --no-transfer-progress"
cache:
  paths:
    - .m2
stages:
  - build
  - package
  - deploy
build:
  stage: build
  script:
    - echo $MAVEN_HOME
    - echo $JAVA_HOME
    - echo $PATH
    - export PATH=$JAVA_HOME/bin:$MAVEN_HOME/bin:$PATH
    - "mvn $MAVEN_CLI_OPTS clean package"